### ISSUE TITLE
multiple transitions

### ISSUE THREAD

**Issue by tgoldenberg** [oblador/react-native-animatable#6] opened 2015-11-22 17:07 UTC
Great project! How would I add multiple transitions to a component? i.e., I want an `Animated.Image` to have a `transition={['width', 'height']} transitionValue={[this.state.width, this.state.height]}`

How would you suggest going about this, or is this something that can be easily added to the project?

Thanks!

**Comment by oblador** [comment] 2015-11-23 00:56
Hi, 

I'm working on a syntax which is more like the CSS `transition` rule. This will allow for a really clean way to do this, basically just define which (or all) styles that should transition and then define the rest via `style` the prop. 

For now, most cases can be solved by simply nesting `Animatable.*` elements. 

Closing because dupe of https://github.com/oblador/react-native-animatable/issues/4

**Closed by oblador** 2015-11-23 00:56 UTC
