### ISSUE TITLE
`onAnimationBegin` and `onAnimationEnd` with `transition` prop?

### ISSUE THREAD

**Issue by alexandergunnarson** [oblador/react-native-animatable#177] opened 2018-02-11 05:07 UTC
It would be nice if the `onAnimationBegin` and `onAnimationEnd` callbacks could be called if either the `animation` *or* the `transition` prop is present (non-null). The alternative is recreating the `transition` functionality in the `animation` definition in order to trick the callbacks into being called, which is not ideal.

Is this straightforward to implement?

**Comment by mattyclarkson** [comment] 2018-04-24 10:04
Duplicate of #85

**Comment by oblador** [comment] 2018-05-31 19:46
`onTransitionBegin` and `onTransitionEnd` are now available in [1.3.0](https://github.com/oblador/react-native-animatable/releases/tag/v1.3.0).

**Closed by oblador** 2018-05-31 19:46 UTC
